import { classifyArtifact, ACTIONS } from './update-classifier.js';

/**
 * What `install` does with one artifact, for every target and every artifact
 * class. Pure: it decides, the caller writes.
 *
 * This lives in lib/ rather than in an adapter because all three targets need
 * the same decisions and only the *layout* differs — claude writes
 * `{id}/BODY.md` folders, windsurf writes chunked `-part-N.md` files. Sharing
 * the decision while keeping the writes separate is what stops a second copy of
 * this switch from appearing per adapter, which is exactly how windsurf ended up
 * with no ownership model at all.
 *
 * Mirrors ACTION_HANDLERS in bin/update.js — same actions, different verbs.
 */

/**
 * How a skipped local edit can be resolved. Rules get the shorter hint because
 * `update` genuinely cannot merge them — it skips every `rule:` lock entry
 * (RULE_SKIP in bin/update.js); rules are regenerated by install/sync only.
 */
export const MERGE_HINT = {
  artifact: 'run `update` to merge, or `install --force` to overwrite',
  rule: 'run `install --force` to overwrite',
};

/** Every state whose outcome is "write our render, lock our checksum". */
const writeFresh = ({ freshEntry }) => ({ writeBody: true, lock: freshEntry });

/**
 * `install` never merges. A local edit is skipped with a hint pointing at the
 * command that can resolve it, and the id stays tracked so the next run
 * re-detects it — unless --force, which resets our own file.
 */
function skipLocalEdits({ freshEntry, lockEntry, force, mergeHint }) {
  if (force) return { writeBody: true, lock: freshEntry };
  return { writeBody: false, lock: lockEntry, warning: `local edits present — skipped (${mergeHint}).` };
}

/**
 * One pure planner per classifier action. Each returns
 * { writeBody, lock, warning? } — `lock` is the entry to carry into the new
 * lockfile, and null drops the id from it entirely.
 *
 * REMOVED has no entry on purpose: install only iterates artifacts that exist
 * upstream, so there is always an upstream side to compare against.
 */
const INSTALL_HANDLERS = Object.freeze({
  [ACTIONS.NEW]: writeFresh,
  [ACTIONS.UNCHANGED]: writeFresh,
  [ACTIONS.AUTO_APPLY]: writeFresh,
  // MISSING_ON_DISK restores the file here and in `update` alike — see the
  // contract in lib/update-classifier.js.
  [ACTIONS.MISSING_ON_DISK]: writeFresh,

  // The file carries our marker but is not in the lockfile. Keep it, register
  // the on-disk content as the merge baseline, and defer any plugin overwrite
  // to `update`.
  [ACTIONS.ADOPT]: ({ freshEntry, onDiskChecksum }) => ({
    writeBody: false,
    lock: { ...freshEntry, checksum: onDiskChecksum },
    warning: 'existing marked file not in lockfile — adopted as baseline (run `update` to merge plugin changes).',
  }),

  [ACTIONS.LOCAL_ONLY]: skipLocalEdits,
  [ACTIONS.CONFLICT]: skipLocalEdits,

  // An owner-authored file occupies this id. Sacred even under --force; the
  // owner deletes it to hand the id over.
  [ACTIONS.COLLISION]: () => ({
    writeBody: false,
    lock: null,
    warning: 'owner-authored file occupies this id — left untouched, not added to lockfile.',
  }),

  [ACTIONS.DISOWNED]: () => ({
    writeBody: false,
    lock: null,
    warning: 'on-disk file is no longer recognisably plugin-generated — left untouched, dropped from lockfile.',
  }),
});

/**
 * Classifies one artifact and returns the plan for it. Writing is left to the
 * caller: every call site writes to a different layout.
 *
 * @param {object} opts
 * @param {string} opts.key            — "<kind>:<id>", used for warning prefixes
 * @param {object} opts.freshEntry     — the lock entry our current render would produce
 * @param {object} opts.upstream       — {version, checksum} of the current render
 * @param {object|null} opts.lockEntry — prior lockfile entry for this key
 * @param {object|null} opts.installedEntry — on-disk snapshot {checksum, hasMarker}
 * @param {'marker'|'checksum'|'none'} opts.ownership
 * @param {string} opts.mergeHint      — one of MERGE_HINT
 * @param {boolean} opts.force
 * @param {object} opts.warn           — writable stream
 * @returns {{writeBody: boolean, lock: object|null}}
 */
export function planInstall({ key, freshEntry, upstream, lockEntry, installedEntry, ownership, mergeHint, force, warn }) {
  const onDiskChecksum = installedEntry ? installedEntry.checksum : null;
  const action = classifyArtifact({
    upstream,
    lockEntry,
    onDiskChecksum,
    hasMarker: installedEntry?.hasMarker ?? false,
    ownership,
  });

  const handler = INSTALL_HANDLERS[action];
  if (!handler) throw new Error(`planInstall: unhandled action "${action}" for ${key}`);

  const plan = handler({ freshEntry, lockEntry, onDiskChecksum, force, mergeHint });
  if (plan.warning) warn.write(`${key}: ${plan.warning}\n`);
  return plan;
}
