import { readFileSync, writeFileSync } from 'node:fs';
import { load as parseYaml, dump as dumpYaml, CORE_SCHEMA } from 'js-yaml';

const LOCKFILE_NAME = 'spovishun-skills.lock.yaml';

/**
 * Writes a lockfile to disk.
 *
 * @param {string} filePath  — absolute path to write (typically join(cwd, LOCKFILE_NAME))
 * @param {object} opts
 * @param {string}   opts.pluginVersion   — semver of the spovishun-skills package
 * @param {string}   opts.target          — e.g. "claude"
 * @param {Array}    opts.artifacts       — [{kind, id, version, checksum}]
 * @param {Function} [opts.now]           — () => Date  — injectable clock for tests
 */
export function writeLockfile(filePath, { pluginVersion, target, artifacts, now = () => new Date() }) {
  const sorted = [...artifacts].sort((a, b) => {
    if (a.kind !== b.kind) return a.kind.localeCompare(b.kind);
    return a.id.localeCompare(b.id);
  });

  const data = {
    generatedAt: now().toISOString(),
    pluginVersion,
    target,
    artifacts: sorted.map(({ kind, id, version, checksum }) => ({ kind, id, version, checksum })),
  };

  const header =
    '# spovishun-skills.lock.yaml\n' +
    '# Auto-generated by `spovishun-skills install`. Do not edit manually.\n' +
    '# Commit this file to version control.\n\n';

  writeFileSync(filePath, header + dumpYaml(data, { lineWidth: 120 }), 'utf8');
}

/**
 * Reads and parses an existing lockfile.
 *
 * @param {string} filePath
 * @returns {object|null}  — parsed lockfile data, or null if file does not exist
 */
export function readLockfile(filePath) {
  let raw;
  try {
    raw = readFileSync(filePath, 'utf8');
  } catch {
    return null;
  }
  return parseYaml(raw, { schema: CORE_SCHEMA });
}

export { LOCKFILE_NAME };
